site_name: Mustard's docs
repo_name: Mustard's github
repo_url: https://github.com/wxmustard/note2
heme:
        name: 'material'
nav:
        - 'help':
                - '快熟开始': 'help/start.md'
        - 'python notes':
                - '数据结构': 'python/Chapter7.md'
